# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-zscaler
  description: This component is responsible for provisioning ZScaler Private Access Connector instances on Amazon Linux 2 AMIs
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component




